### ISSUE TITLE
Sponsor image missing in SponsorIntro.js

### ISSUE THREAD

**Issue by BraydenTW** [MasonWang025/yam-website#3]
Hi, I was just taking a look at the website and noticed that there was a logo that couldn’t be loaded onto the Sponsor’s section in the homepage. 

It is located here **at lines 43 and 44* both linking to the same logo in `SponsorIntro.js`:

```

<div class="grid">
     <div><img src="https://www.halberesford.com/content/images/2018/07/null.png" alt=""></img></div>
      <div><img src="https://www.halberesford.com/content/images/2018/07/null.png" alt=""></img></div>
      <div><img src="https://i.pinimg.com/originals/50/55/4e/50554e7975371dbbdc8b5a39d39f0cb8.png" alt=""></img></div>
</div>

```

When I look up the [image url](https://www.halberesford.com/content/images/2018/07/null.png), I get this result:

![152B2559-F2A5-4517-910D-A9D1B1B5F77F](https://user-images.githubusercontent.com/47185402/114913109-6ce64000-9de6-11eb-97f3-5348b61b5638.jpeg)

I would submit a PR fixing this, however I don’t even know which sponsor you are referring to.

Hope this helps.

**Comment by kiranreddy75** [comment]
Hi, It's not a Sponsor image, they're blank images with white background, It's been added to the grid just to make the sponsor image center of the page.
<img width="602" alt="Screen Shot 2021-04-28 at 8 56 00 AM" src="https://user-images.githubusercontent.com/34183050/116434871-a9ab3180-a7ff-11eb-8657-c3f80038cf40.png">

**Comment by kiranreddy75** [comment]
I'll remove these blank image and make the sponsor image center of page and responsive.
